"""
Django settings for mycourse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)=gx8&dg4@=ya36_h=++i1pm03=v7aq%hy6(w(ju8wm_o+v*p7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'courses',
]
SITE_ID = 1

# Thêm các setting này
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Authentication backends: include allauth backend so login/verification via email works
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mycourse.urls'

import os

# Load environment variables from a .env file at project root (optional)
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # ← QUAN TRỌNG, ĐỂ NHẬN FILE GLOBAL TEMPLATES
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mycourse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'courses/static'),
]

# Directory where `collectstatic` will collect static files for production
# Set to a folder at project root; change if you prefer another location.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email Configuration
# Prefer reading email credentials from environment for safety. For local testing
# set the env vars below (see README comments). Default backend is SMTP for
# real delivery; set DJANGO_EMAIL_BACKEND to console backend to print emails.
# Email Configuration
# By default this project will use Gmail SMTP to send confirmation emails.
# You can either set the credentials via environment variables (recommended),
# or fill them directly below (NOT recommended for public repos).

# Determine email backend. Priority:
# 1) DJANGO_EMAIL_BACKEND env var (explicit)
# 2) If DEBUG and USE_SMTP not set/false -> console backend (easy dev debugging)
# 3) Otherwise use SMTP backend
DJANGO_EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND')
if DJANGO_EMAIL_BACKEND:
    EMAIL_BACKEND = DJANGO_EMAIL_BACKEND
else:
    if DEBUG and os.environ.get('USE_SMTP', '').lower() not in ('1', 'true', 'yes'):
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP configuration (defaults)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') in ('True', 'true', '1')

# --- Configure below: either set env vars, or replace the placeholders directly. ---
# Example (fill with your Gmail and 16-char app password):
# EMAIL_HOST_USER = 'siculakeomut123@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_16_char_app_password'

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Học Lập Trình <{EMAIL_HOST_USER}>')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', EMAIL_HOST_USER)

# django-allauth email settings (enable email verification flow)
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = os.environ.get('ACCOUNT_EMAIL_VERIFICATION', 'mandatory')
ACCOUNT_AUTHENTICATION_METHOD = os.environ.get('ACCOUNT_AUTHENTICATION_METHOD', 'username_email')
# Use http for local dev links (allauth uses this to build confirmation URLs)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = os.environ.get('ACCOUNT_DEFAULT_HTTP_PROTOCOL', 'http')

# When user clicks email confirmation link, confirm on GET and log them in automatically.
# This makes the confirmation link immediately activate the account and sign the user in.
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Development-only flag to allow auto-login on email confirmation (useful for QA).
# Defaults to True in DEBUG, False otherwise. Set to '0'/'false' in .env to disable.
DEV_AUTO_LOGIN_ON_CONFIRM = os.environ.get(
    'DEV_AUTO_LOGIN_ON_CONFIRM', '1' if DEBUG else '0'
).lower() in ('1', 'true', 'yes')

# Optional site domain override for confirmation links
SITE_DOMAIN = os.environ.get('SITE_DOMAIN', '')

# Grappelli admin title (customize as you like)
GRAPPELLI_ADMIN_TITLE = os.environ.get('GRAPPELLI_ADMIN_TITLE', 'Học Lập Trình Admin')